# Generated by Django 5.2.8 on 2025-11-12 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.IntegerField(unique=True)),
                ('exam_title', models.CharField(max_length=200)),
                ('exam_marks', models.IntegerField(default=100)),
                ('exam_date_time', models.DateTimeField()),
                ('exam_duration', models.IntegerField(default=60)),
                ('exam_question', models.FileField(default='exam/questions/sample.pdf', upload_to='exam/questions')),
                ('examiner', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.examiner')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptedExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit', models.BooleanField(default=False)),
                ('examinee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.examinee')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamManagement.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=100)),
                ('time_limit', models.IntegerField(default=60)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamManagement.exam')),
            ],
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('ques_marks', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamManagement.question')),
            ],
        ),
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('ques_marks', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamManagement.question')),
            ],
        ),
    ]
