# Generated by Django 5.2.8 on 2025-11-12 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('ExamManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corr_ans', models.CharField(max_length=200)),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ExamManagement.mcqquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ExamineeAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FileField(default='exam/answers/sample.pdf', upload_to='exam/answers/')),
                ('graded', models.BooleanField(default=False)),
                ('done_late', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamManagement.exam')),
                ('examinee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.examinee')),
            ],
        ),
        migrations.CreateModel(
            name='ExamineeMCQAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_option', models.CharField(blank=True, max_length=200, null=True)),
                ('examinee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.examinee')),
                ('mcq_question', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamManagement.mcqquestion')),
            ],
        ),
    ]
